//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleStringSplitApplication
{
    using CodeFirstStoreFunctions;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TestSampleEntities : DbContext
    {
        public TestSampleEntities()
            : base("name=TestSampleEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Add(new FunctionsConvention<TestSampleEntities>("dbo"));
        }

        public virtual DbSet<Person> People { get; set; }
    }
}
